
INSERT INTO public.site_content (key, value) VALUES
  ('google_reviews_url', 'https://www.google.com/search?q=Design+Cleaning+DMV'),
  ('gift_card_url', ''),
  ('testimonial_1_text', 'Design Cleaning made the whole experience so easy. Booked online in 5 minutes, they showed up on time, and my home was spotless. This is exactly what I needed.'),
  ('testimonial_1_name', 'Amanda R.'),
  ('testimonial_1_location', 'Gaithersburg'),
  ('testimonial_2_text', 'I''ve tried other cleaning services before but Design Cleaning is on a different level. Professional, reliable, and the results are consistently excellent.'),
  ('testimonial_2_name', 'James T.'),
  ('testimonial_2_location', 'Washington DC'),
  ('testimonial_3_text', 'The membership plan is a game changer. I never have to think about scheduling — my home is always clean and the pricing is unbeatable.'),
  ('testimonial_3_name', 'Sofia M.'),
  ('testimonial_3_location', 'Gaithersburg'),
  ('testimonial_4_text', 'Used them for a move-out clean and got my full deposit back. They cleaned things I didn''t even think about. Absolutely worth every penny.'),
  ('testimonial_4_name', 'David L.'),
  ('testimonial_4_location', 'Washington DC'),
  ('testimonial_5_text', 'Finally a cleaning service that actually feels professional. The booking was smooth, communication was great, and the clean was immaculate.'),
  ('testimonial_5_name', 'Rachel K.'),
  ('testimonial_5_location', 'Gaithersburg'),
  ('city_gaithersburg_intro', 'Design Cleaning provides professional, reliable home cleaning services in Gaithersburg. Book online in minutes — simple pricing, no hassle.'),
  ('city_washington-dc_intro', 'Design Cleaning provides professional, reliable home cleaning services in Washington DC. Book online in minutes — simple pricing, no hassle.'),
  ('city_silver-spring_intro', 'Design Cleaning provides professional, reliable home cleaning services in Silver Spring. Book online in minutes — simple pricing, no hassle.'),
  ('city_rockville_intro', 'Design Cleaning provides professional, reliable home cleaning services in Rockville. Book online in minutes — simple pricing, no hassle.'),
  ('city_bethesda_intro', 'Design Cleaning provides professional, reliable home cleaning services in Bethesda. Book online in minutes — simple pricing, no hassle.'),
  ('city_germantown_intro', 'Design Cleaning provides professional, reliable home cleaning services in Germantown. Book online in minutes — simple pricing, no hassle.'),
  ('city_potomac_intro', 'Design Cleaning provides professional, reliable home cleaning services in Potomac. Book online in minutes — simple pricing, no hassle.'),
  ('city_bowie_intro', 'Design Cleaning provides professional, reliable home cleaning services in Bowie. Book online in minutes — simple pricing, no hassle.'),
  ('city_college-park_intro', 'Design Cleaning provides professional, reliable home cleaning services in College Park. Book online in minutes — simple pricing, no hassle.'),
  ('city_laurel_intro', 'Design Cleaning provides professional, reliable home cleaning services in Laurel. Book online in minutes — simple pricing, no hassle.')
ON CONFLICT (key) DO NOTHING;
